export { LeftArrowCircle } from "./leftArrowCirlce";
export { RightArrowCircle } from "./rightArrowCirlce";
export { Telegram } from "./telegram";
export { WA } from "./wa";
export { Cart } from "./cart";
export { Inst } from "./inst";
export { Search } from "./search";
export { Checkbox } from "./checkbox";
export { Close } from "./close";
